name: testing

on:
  push:
    branches:
      - "**"

env:
  go_version: "1.20.1"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      COVER_FILE: coverage.out
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version}}
      - run: go mod tidy
      - name: Run unit tests
        run: go test -coverprofile=$COVER_FILE -covermode=atomic ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}